# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


TWITTER_KEY: HnWWSVa6osxd6ETcn1MGw
TWITTER_SECRET: lVU9HGVnVhCja1vKGjJeFtVa1jSOxTRhRQbUI2ojEtY
TWITTER_OAUTH_TOKEN: 1296747229-oQMig3C2z2Gjt9wFoQZyxPCdeeksREU9KByg4e2
TWITTER_OAUTH_SECRET: bBgt8Gtm8Pv5j1kGIbVwOvpuUBjfCRcv3X3A3BAu5KQ
KLOUT_KEY: dqgfat856gv85kwe4f6t2xrx
KLOUT_SHARED: 32AMFfTY
KLOUT_API_V2: dqgfat856gv85kwe4f6t2xrx
